name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Load publisher key
      env:
        PUBLISHER_KEY: ${{ secrets.PUBLISHER_KEY }}
      run: echo "${PUBLISHER_KEY}" > publisher-key.json
    - name: Load keystore
      id: write_file
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'keystore.jks'
        encodedString: ${{ secrets.KEYSTORE_BASE64 }}
    - name: Build with Gradle
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      run: |
        ./gradlew publishReleaseBundle
        -PversionCode="${GITHUB_RUN_NUMBER}"
        -Pkeystore=keystore.jks
        -PkeystorePassword="${KEYSTORE_PASSWORD}"
        -PkeyAlias="${KEYSTORE_KEY_ALIAS}"
        -PkeyPassword="${KEYSTORE_KEY_PASSWORD}"
